# Generated by Django 3.0.9 on 2021-01-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20181115_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
    ]
