# Generated by Django 3.0.6 on 2020-07-09 12:50

import Avalancheutfpr.services
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campanhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('local', models.CharField(max_length=255)),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('QRcode', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data de Realização')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Ação Social',
                'verbose_name_plural': 'Ações Sociais',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField(max_length=500)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data do contato')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='diretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area')),
                ('foto', stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('QRcode', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('data', models.DateField(blank=True, null=True)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('QRcode', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Modalidade de E-sports',
                'verbose_name_plural': 'Modalidades de E-sports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='inscricao_campanhas_sociais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('Ra', models.CharField(max_length=30, verbose_name='Registro Acadêmico')),
                ('telefone', models.CharField(max_length=30, verbose_name='Contato')),
                ('Compareceu', models.BooleanField(default=False)),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da inscrição')),
            ],
            options={
                'verbose_name': 'Ações Sociais - inscrições',
                'verbose_name_plural': 'Ações Sociais - inscrições',
                'ordering': ['campanha'],
            },
        ),
        migrations.CreateModel(
            name='inscricao_E_sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('Ra', models.CharField(max_length=30, verbose_name='Registro Acadêmico')),
                ('telefone', models.CharField(max_length=30, verbose_name='Contato')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da inscrição')),
            ],
            options={
                'verbose_name': 'E-sports - inscrições',
                'verbose_name_plural': 'E-sports - inscrições',
                'ordering': ['game'],
            },
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('tag', models.CharField(max_length=255)),
                ('foto', stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'mídia',
                'verbose_name_plural': ' mídias',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='modalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('Contatos', models.TextField(verbose_name='Contatos da Modalidade')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='inscricao_modalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('curso', models.CharField(max_length=255, verbose_name='Curso')),
                ('Ra', models.CharField(max_length=30, verbose_name='Registro Acadêmico')),
                ('telefone', models.CharField(max_length=30, verbose_name='Contato')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da inscrição')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.modalidades', verbose_name='Modalidade')),
            ],
            options={
                'verbose_name': 'Modalidades - inscrições',
                'verbose_name_plural': 'Modalidades - inscrições',
                'ordering': ['modalidade'],
            },
        ),
    ]
