# Generated by Django 3.0.6 on 2020-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0002_auto_20200709_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diretoria',
            options={'ordering': ['name'], 'verbose_name': 'Diretor', 'verbose_name_plural': 'Diretores'},
        ),
        migrations.RemoveField(
            model_name='diretoria',
            name='area',
        ),
        migrations.RemoveField(
            model_name='diretoria',
            name='video',
        ),
        migrations.AddField(
            model_name='diretoria',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='diretoria',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='diretoria',
            name='intagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
    ]
