# Generated by Django 3.0.6 on 2020-09-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0009_auto_20200911_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoria',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Presidente'), (2, 'Vice Presidente'), (3, 'Diretor Geral')], verbose_name='Cargo'),
        ),
    ]
