# Generated by Django 3.0.6 on 2020-07-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0004_auto_20200721_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhas',
            name='previa',
            field=models.TextField(default='tem uma', verbose_name='Prévia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='previa',
            field=models.TextField(default='tem uma', verbose_name='Prévia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='previa',
            field=models.TextField(default='tem uma', verbose_name='Prévia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modalidades',
            name='previa',
            field=models.TextField(default='tem uma', verbose_name='Prévia'),
            preserve_default=False,
        ),
    ]
