# Generated by Django 3.0.6 on 2020-09-03 02:28

import Avalancheutfpr.services
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0006_auto_20200722_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='competicoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('previa', models.TextField(verbose_name='Prévia')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('image', stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=300, verbose_name='Time da casa')),
                ('time2', models.CharField(max_length=300, verbose_name='Time visitante')),
                ('imgtime1', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Logotipo time da casa')),
                ('imgtime2', stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path, verbose_name='logotipo time visitante')),
                ('placart1', models.IntegerField(verbose_name='Pontos do time da casa')),
                ('placart2', models.IntegerField(verbose_name='Pontos do time visitante')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='Horário do jogo')),
                ('local', models.CharField(blank=True, max_length=300, verbose_name='Local')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do jogo')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.competicoes', verbose_name='Competição')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo da jogada')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do Lance')),
                ('tempo', models.TimeField(auto_now_add=True, verbose_name='Tempo')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.jogos', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lance',
            },
        ),
    ]
