# Generated by Django 3.0.6 on 2020-09-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0008_auto_20200911_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoria',
            name='cargo',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Vice Presidente', 'Vice Presidente'), ('Diretor Geral', 'Diretor Geral')], max_length=255, verbose_name='Cargo'),
        ),
    ]
