# Generated by Django 3.0.9 on 2021-02-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0012_cheers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diretoria',
            old_name='intagram',
            new_name='instagram',
        ),
    ]
