# Generated by Django 3.0.6 on 2020-06-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
