# Generated by Django 3.0.6 on 2020-06-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200603_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
