# Generated by Django 3.0.6 on 2020-06-10 15:41

import Avalancheutfpr.services
import autoslug.fields
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20200603_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='url',
        ),
        migrations.AddField(
            model_name='produtos',
            name='estoque',
            field=models.IntegerField(default=10, verbose_name='Quantidade em estoque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='p_socio',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=6, verbose_name='Preço para Sócio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=6, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='padra', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='thumb',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path, verbose_name='thumbnail'),
        ),
    ]
