# Generated by Django 3.0.6 on 2020-06-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200610_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='estoque',
            field=models.PositiveIntegerField(verbose_name='Quantidade em estoque'),
        ),
        migrations.CreateModel(
            name='itemcarrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=255, verbose_name='Chave do carrinho')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade do item no carrinho')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produtos', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Item no carrinho',
                'verbose_name_plural': 'Itens no carrinho',
                'ordering': ['chave'],
            },
        ),
    ]
