# Generated by Django 3.0.6 on 2020-07-17 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200709_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtobase',
            options={'ordering': ['name'], 'verbose_name': 'Produto Base', 'verbose_name_plural': 'Produtos Base'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['name'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterField(
            model_name='produtos',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produtos', related_query_name='Produtos_Query', to='ecommerce.produtobase', verbose_name='Base'),
        ),
    ]
