# Generated by Django 3.0.6 on 2020-06-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20200610_1306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('chave', 'produto')},
        ),
    ]
