# Generated by Django 3.0.6 on 2020-06-12 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0006_auto_20200610_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Compra Concluída'), (2, 'Entregue'), (3, 'Cancelada')], default=0, verbose_name='Status do pedido')),
                ('pagamento', models.CharField(choices=[('PagSeguro', 'PagSeguro'), ('PayPal', 'Paypal')], max_length=255, verbose_name='Opção de Pagamento')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='itemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade do item no carrinho')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='ecommerce.pedidos', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.produtos', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do Pedidos',
            },
        ),
    ]
