# Generated by Django 3.0.6 on 2020-07-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20200716_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtobase',
            name='destaque',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=30, null=True),
        ),
    ]
