# Generated by Django 3.0.6 on 2020-06-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_itempedido_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pagamento',
            field=models.CharField(choices=[('Deposito', 'Depósito'), ('PagSeguro', 'PagSeguro'), ('PayPal', 'Paypal')], default='Deposito', max_length=255, verbose_name='Opção de Pagamento'),
        ),
    ]
