# Generated by Django 3.0.6 on 2020-07-22 16:11

import Avalancheutfpr.services
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_produtobase_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtobase',
            name='thumb',
            field=stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path, verbose_name='thumbnail'),
        ),
    ]
