# Generated by Django 3.0.6 on 2020-06-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200612_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itens', to='ecommerce.pedidos', verbose_name='Pedido'),
        ),
    ]
