# Generated by Django 3.0.6 on 2020-08-31 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200722_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='produtobase',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 8, 31, 5, 41, 3, 696919, tzinfo=utc), verbose_name='Data de Criação'),
            preserve_default=False,
        ),
    ]
