# Generated by Django 3.0.6 on 2020-06-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200612_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pagamento',
            field=models.CharField(choices=[('Deposito', 'Depósito'), ('PagSeguro', 'PagSeguro'), ('PicPay', 'PicPay')], default='Deposito', max_length=255, verbose_name='Opção de Pagamento'),
        ),
    ]
