# Generated by Django 3.1.1 on 2020-09-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria',
            new_name='catalogo',
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['name'], 'verbose_name': 'Catalogo', 'verbose_name_plural': 'Catalogo'},
        ),
    ]
