# Generated by Django 3.0.6 on 2020-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200615_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Pagamento Concluído'), (2, 'Entregue'), (3, 'Cancelada')], default=0, verbose_name='Status do pedido'),
        ),
    ]
