# Generated by Django 3.1.1 on 2020-09-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20200930_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtobase',
            name='Catalogo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='ecommerce.catalogo', verbose_name='Catalogo'),
            preserve_default=False,
        ),
    ]
