# Generated by Django 3.0.6 on 2020-08-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engenhariadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='pagamento',
            field=models.CharField(choices=[('Deposito', 'Depósito'), ('PicPay', 'PicPay'), ('Presencial', 'Presencial')], default='Deposito', max_length=255, verbose_name='Opção de Pagamento'),
        ),
    ]
