# Generated by Django 3.0.6 on 2020-07-08 08:14

import Avalancheutfpr.services
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Engenhariadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Valor Depositado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aguardando Validação'), (1, 'Pagamento Validado')], default=0, verbose_name='Status da Validação'),
        ),
        migrations.AddField(
            model_name='pagamentos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='inscrito', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engenhariadas',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='image',
            field=stdimage.models.StdImageField(blank=True, help_text='Caso o pagamento for via DEPOSITO NA CONTA DA CAIXA enviar imagem do comprovante de pagamento', null=True, upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='pagamento',
            field=models.CharField(choices=[('Deposito', 'Depósito'), ('PicPay', 'PicPay')], default='Deposito', max_length=255, verbose_name='Opção de Pagamento'),
        ),
    ]
