# Generated by Django 3.0.6 on 2020-07-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engenhariadas', '0002_auto_20200708_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceladao',
            name='engenhariadas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EP', to='Engenhariadas.engenhariadas', verbose_name='Edição do Engenhariadas'),
        ),
    ]
