# Generated by Django 3.0.6 on 2020-07-09 12:50

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Nome_completo', models.CharField(max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True, verbose_name='Diretor')),
                ('Socio', models.BooleanField(default=False, null=True)),
                ('CPF', localflavor.br.models.BRCPFField(max_length=14, unique=True)),
                ('Curso', models.CharField(choices=[('Nenhum', 'Nenhum'), ('Administração', 'Administração'), ('Arquitetura e Urbanismo', 'Arquitetura e Urbanismo'), ('Bacharelado em Química', 'Bacharelado em Química'), ('Comunicação Organizacional', 'Comunicação Organizacional'), ('Design', 'Design'), ('Educação Física', 'Educação Física'), ('Engenharia Ambiental e Sanitária', 'Engenharia Ambiental e Sanitária'), ('Engenharia Civil', 'Engenharia Civil'), ('Engenharia de Computação', 'Engenharia de Computação'), ('Engenharia de Controle e Automação', 'Engenharia de Controle e Automação'), ('Engenharia Elétrica', 'Engenharia Elétrica'), ('Engenharia Eletrônica', 'Engenharia Eletrônica'), ('Engenharia Mecânica', 'Engenharia Mecânica'), ('Engenharia Mecatrônica', 'Engenharia Mecatrônica'), ('Licenciatura em Física', 'Licenciatura em Física'), ('Licenciatura em Letras Inglês', 'Licenciatura em Letras Inglês'), ('Licenciatura em Letras Português', 'Licenciatura em Letras Português'), ('Licenciatura em Matemática', 'Licenciatura em Matemática'), ('Licenciatura em Química', 'Licenciatura em Química'), ('Sistemas da Informação', 'Sistemas da Informação'), ('Tecnologia em Controle e Automação', 'Tecnologia em Controle e Automação'), ('Tecnologia em Design Gráfico', 'Tecnologia em Design Gráfico'), ('Tecnologia em Radiologia', 'Tecnologia em Radiologia'), ('Tecnologia em Sistemas de Telecomunicação', 'Tecnologia em sistemas de Telecomunicação')], max_length=255, null=True)),
                ('Registro_Academico', models.CharField(blank=True, help_text='Caso não é aluno da utfpr,deixar em Branco', max_length=255, null=True, unique=True)),
                ('Telefone', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['Nome_completo'],
            },
        ),
    ]
