# Generated by Django 3.0.6 on 2020-07-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Nome_completo',
            field=models.CharField(help_text='Digite o seu nome COMPLETO', max_length=255, null=True, unique=True),
        ),
    ]
