# Generated by Django 3.0.6 on 2020-08-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0002_auto_20200721_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Registro_Academico',
            field=models.IntegerField(blank=True, help_text='Caso não é aluno da utfpr,deixar em Branco', null=True, unique=True),
        ),
    ]
