# Generated by Django 3.0.5 on 2020-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0003_auto_20200520_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Nome_completo',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
