# Generated by Django 3.0.6 on 2020-09-10 02:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0003_auto_20200822_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR'),
        ),
    ]
