# Generated by Django 3.0.5 on 2020-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0004_auto_20200520_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Telefone',
            field=models.CharField(default='00000000000', max_length=13),
        ),
    ]
