# Generated by Django 3.0.6 on 2020-09-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0004_auto_20200909_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termos',
            field=models.BooleanField(default=True, verbose_name='Termo de Aceite'),
        ),
    ]
