# Generated by Django 3.0.5 on 2020-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0005_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telefone',
            field=models.CharField(max_length=13),
        ),
    ]
