# Generated by Django 3.1.1 on 2020-09-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0005_user_termos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='Genero',
            field=models.CharField(choices=[('Nenhum', 'Nenhum'), ('Administração', 'Administração'), ('Arquitetura e Urbanismo', 'Arquitetura e Urbanismo'), ('Bacharelado em Química', 'Bacharelado em Química'), ('Comunicação Organizacional', 'Comunicação Organizacional'), ('Design', 'Design'), ('Educação Física', 'Educação Física'), ('Engenharia Ambiental e Sanitária', 'Engenharia Ambiental e Sanitária'), ('Engenharia Civil', 'Engenharia Civil'), ('Engenharia de Computação', 'Engenharia de Computação'), ('Engenharia de Controle e Automação', 'Engenharia de Controle e Automação'), ('Engenharia Elétrica', 'Engenharia Elétrica'), ('Engenharia Eletrônica', 'Engenharia Eletrônica'), ('Engenharia Mecânica', 'Engenharia Mecânica'), ('Engenharia Mecatrônica', 'Engenharia Mecatrônica'), ('Licenciatura em Física', 'Licenciatura em Física'), ('Licenciatura em Letras Inglês', 'Licenciatura em Letras Inglês'), ('Licenciatura em Letras Português', 'Licenciatura em Letras Português'), ('Licenciatura em Matemática', 'Licenciatura em Matemática'), ('Licenciatura em Química', 'Licenciatura em Química'), ('Sistemas da Informação', 'Sistemas da Informação'), ('Tecnologia em Controle e Automação', 'Tecnologia em Controle e Automação'), ('Tecnologia em Design Gráfico', 'Tecnologia em Design Gráfico'), ('Tecnologia em Radiologia', 'Tecnologia em Radiologia'), ('Tecnologia em Sistemas de Telecomunicação', 'Tecnologia em sistemas de Telecomunicação')], max_length=255, null=True, verbose_name='Sexo'),
        ),
    ]
