# Generated by Django 3.1.1 on 2020-09-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0006_auto_20200929_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não-Binario', 'Não-Binario')], max_length=255, null=True, verbose_name='Sexo'),
        ),
    ]
