# Generated by Django 3.0.5 on 2020-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0006_auto_20200522_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Registro_Academico',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
