# Generated by Django 3.0.5 on 2020-05-29 20:41

from django.db import migrations, models
import localflavor.br.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0007_auto_20200524_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CPF',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[localflavor.br.validators.BRCPFValidator]),
        ),
    ]
