# Generated by Django 3.1.1 on 2020-09-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0008_auto_20200929_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
