# Generated by Django 3.0.5 on 2020-05-29 20:51

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0008_auto_20200529_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CPF',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
    ]
