# Generated by Django 3.1.1 on 2020-09-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0009_auto_20200929_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
