# Generated by Django 3.0.6 on 2020-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0009_auto_20200529_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['Nome_completo'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, null=True, verbose_name='Diretor'),
        ),
    ]
