# Generated by Django 3.0.6 on 2020-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0010_auto_20200610_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Registro_Academico',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
