# Generated by Django 3.0.6 on 2020-06-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0011_auto_20200622_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Registro_Academico',
            field=models.CharField(blank=True, help_text='Caso não é aluno da utfpr,deixar em Branco', max_length=255, null=True, unique=True),
        ),
    ]
