# Generated by Django 3.1.1 on 2020-09-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0011_auto_20200930_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
