# Generated by Django 3.1 on 2020-12-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0013_auto_20201226_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
