# Generated by Django 3.0.9 on 2021-01-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0015_auto_20210114_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Digite o seu nome COMPLETO', max_length=255, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='termos',
            field=models.BooleanField(choices=[(True, 'Aceito'), (False, 'Recusado')], default=True, verbose_name='Termo de Aceite'),
        ),
    ]
