# Generated by Django 3.0.9 on 2021-01-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0016_auto_20210114_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Socio',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True),
        ),
    ]
