# Generated by Django 3.0.6 on 2020-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='previa',
            field=models.TextField(default='tem uma', verbose_name='Prévia'),
            preserve_default=False,
        ),
    ]
