# Generated by Django 3.0.6 on 2020-06-09 15:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='Padrao', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
