# Generated by Django 3.0.6 on 2020-07-22 16:11

import Avalancheutfpr.services
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0005_auto_20200722_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='QRcode',
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='image',
            field=stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='image',
            field=stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path),
        ),
    ]
