# Generated by Django 3.0.6 on 2020-07-21 22:39

import Avalancheutfpr.services
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0003_auto_20200715_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidades',
            name='Contatos',
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='image',
            field=stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path),
        ),
    ]
