# Generated by Django 3.1 on 2020-12-27 02:21

import Avalancheutfpr.services
from django.db import migrations
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0010_auto_20200911_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidades',
            name='logo',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='image',
            field=stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Imagem'),
        ),
    ]
