# Generated by Django 3.0.9 on 2021-01-27 20:13

import Avalancheutfpr.services
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0011_auto_20201226_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('cargo', models.IntegerField(choices=[(1, 'Presidente'), (2, 'Secretária'), (3, 'Tesoureira'), (4, 'Diretora de Marketing'), (5, 'Capitão')], verbose_name='Cargo')),
                ('foto', stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path)),
                ('intagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Direção Cheers',
                'verbose_name_plural': 'Direção Cheers',
                'ordering': ['cargo'],
            },
        ),
    ]
