# Generated by Django 3.0.5 on 2020-05-16 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campanhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('facebook', models.CharField(default='https://www.facebook.com/avalancheutfpr/', max_length=50)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('facebook', models.CharField(default='https://www.facebook.com/avalancheutfpr/', max_length=50)),
                ('instagram', models.CharField(default='https://www.instagram.com/avalancheutfpr/?hl=pt-br', max_length=50)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao_Campanhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Curso', models.CharField(max_length=255)),
                ('Ra', models.CharField(max_length=30)),
                ('Campanha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao_esportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Curso', models.CharField(max_length=255)),
                ('Ra', models.CharField(max_length=30)),
                ('modalidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao_games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Curso', models.CharField(max_length=255)),
                ('Ra', models.CharField(max_length=30)),
                ('Campanha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='modalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('Contatos', models.TextField(default='Diretoria@atleticautfpr.com.br')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('instagram', models.CharField(default='https://www.instagram.com/avalancheutfpr/?hl=pt-br', max_length=50)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=30, null=True)),
            ],
        ),
    ]
