# Generated by Django 3.0.5 on 2020-05-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Eventos'),
        ),
    ]
