# Generated by Django 3.0.5 on 2020-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0002_auto_20200518_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Campanhas'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Eventos'),
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Games'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modalidades'),
        ),
    ]
