# Generated by Django 3.0.5 on 2020-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0003_auto_20200518_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanhas',
            options={'verbose_name': 'Ação Social', 'verbose_name_plural': 'Ações Sociais'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Modalidade de E-sports', 'verbose_name_plural': 'Modalidades de E-sports'},
        ),
        migrations.AlterModelOptions(
            name='inscricao_campanhas',
            options={'verbose_name': 'Ações Sociais - inscrições', 'verbose_name_plural': 'Ações Sociais - inscrições'},
        ),
        migrations.AlterModelOptions(
            name='inscricao_esportes',
            options={'verbose_name': 'Modalidades - inscrições', 'verbose_name_plural': 'Modalidades - inscrições'},
        ),
        migrations.AlterModelOptions(
            name='inscricao_games',
            options={'verbose_name': 'E-sports - inscrições', 'verbose_name_plural': 'E-sports - inscrições'},
        ),
        migrations.AlterModelOptions(
            name='modalidades',
            options={'verbose_name': 'Modalidade', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.RenameField(
            model_name='inscricao_games',
            old_name='Campanha',
            new_name='Game',
        ),
        migrations.RemoveField(
            model_name='campanhas',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='modalidades',
            name='instagram',
        ),
        migrations.AddField(
            model_name='campanhas',
            name='QRcode',
            field=models.ImageField(blank=True, null=True, upload_to='Campanhas'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='QRcode',
            field=models.ImageField(blank=True, null=True, upload_to='Eventos'),
        ),
        migrations.AddField(
            model_name='games',
            name='QRcode',
            field=models.ImageField(blank=True, null=True, upload_to='E_sports'),
        ),
        migrations.AddField(
            model_name='modalidades',
            name='QRcode',
            field=models.ImageField(blank=True, null=True, upload_to='modalidades'),
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='E_sports'),
        ),
        migrations.AlterField(
            model_name='games',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
