# Generated by Django 3.0.5 on 2020-05-20 15:58

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0005_auto_20200520_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhas',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='Campanhas'),
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='Campanhas'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='Eventos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='Eventos'),
        ),
        migrations.AlterField(
            model_name='games',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='E_sports'),
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='E_sports'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='modalidades'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='modalidades'),
        ),
    ]
