# Generated by Django 3.0.5 on 2020-05-20 16:09

import Avalancheutfpr.services
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0006_auto_20200520_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhas',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='games',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='games',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='QRcode',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
    ]
