# Generated by Django 3.0.5 on 2020-05-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0007_auto_20200520_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_campanhas',
            name='Ra',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='Ra',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='Ra',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
