# Generated by Django 3.0.5 on 2020-05-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0008_auto_20200521_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='Ra',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='modalidade',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
