# Generated by Django 3.0.5 on 2020-05-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0009_auto_20200522_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='modalidade',
            field=models.CharField(max_length=255),
        ),
    ]
