# Generated by Django 3.0.5 on 2020-05-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0012_remove_inscricao_esportes_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao_esportes',
            name='inscrito',
            field=models.BooleanField(default=False),
        ),
    ]
