# Generated by Django 3.0.5 on 2020-05-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0013_inscricao_esportes_inscrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao_esportes',
            name='inscrito',
        ),
    ]
