# Generated by Django 3.0.5 on 2020-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0014_remove_inscricao_esportes_inscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao_esportes',
            name='modalidade_id',
            field=models.CharField(default=0, max_length=3, unique=True),
        ),
    ]
