# Generated by Django 3.0.9 on 2021-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0014_bateria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bateria',
            old_name='intagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='cheers',
            old_name='intagram',
            new_name='instagram',
        ),
        migrations.AlterField(
            model_name='bateria',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Presidente'), (2, 'Vice Presidente'), (3, 'Mestre'), (4, 'Marketing'), (5, 'Financeiro'), (6, 'Produtos'), (7, 'Materiais')], verbose_name='Cargo'),
        ),
    ]
