# Generated by Django 3.0.5 on 2020-05-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0015_inscricao_esportes_modalidade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='modalidade_id',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
