# Generated by Django 3.0.5 on 2020-05-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0016_auto_20200522_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao_esportes',
            old_name='modalidade_id',
            new_name='tag',
        ),
    ]
