# Generated by Django 3.0.5 on 2020-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0017_auto_20200522_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao_esportes',
            name='tag',
        ),
        migrations.AddField(
            model_name='inscricao_esportes',
            name='Tag',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
