# Generated by Django 3.0.9 on 2021-06-17 09:18

import Avalancheutfpr.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0017_esports'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titúlo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.FileField(blank=True, upload_to='', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
            },
        ),
        migrations.CreateModel(
            name='fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Foto')),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.album')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
