# Generated by Django 3.0.9 on 2021-06-17 10:28

import Avalancheutfpr.services
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0018_album_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='album',
            name='foto',
        ),
        migrations.AddField(
            model_name='album',
            name='capa',
            field=models.FileField(blank=True, upload_to='', verbose_name='Capa'),
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='novo', editable=False, populate_from='titulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Foto'),
        ),
    ]
