# Generated by Django 3.0.9 on 2021-06-17 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0019_auto_20210617_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
