# Generated by Django 3.0.5 on 2020-05-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0020_auto_20200522_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao_campanhas',
            name='tag',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='inscricao_games',
            name='tag',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inscricao_campanhas',
            name='Ra',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='Ra',
            field=models.CharField(max_length=30),
        ),
    ]
