# Generated by Django 3.0.5 on 2020-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0021_auto_20200522_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_campanhas',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
