# Generated by Django 3.0.5 on 2020-05-22 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Avalancheutfpr', '0022_auto_20200522_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao_games',
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='inscricao_games',
            name='Ra',
        ),
        migrations.RemoveField(
            model_name='inscricao_games',
            name='name',
        ),
        migrations.AddField(
            model_name='inscricao_games',
            name='inscrito',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
