# Generated by Django 3.0.5 on 2020-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0023_auto_20200522_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao_games',
            name='inscrito',
        ),
        migrations.AddField(
            model_name='inscricao_games',
            name='Curso',
            field=models.CharField(default='Nenhum', max_length=255),
        ),
        migrations.AddField(
            model_name='inscricao_games',
            name='Ra',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='inscricao_games',
            name='name',
            field=models.CharField(default='Nenhum', max_length=255),
        ),
    ]
