# Generated by Django 3.0.5 on 2020-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0024_auto_20200522_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField(max_length=500)),
            ],
        ),
    ]
