# Generated by Django 3.0.5 on 2020-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0025_contatos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatos',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AddField(
            model_name='inscricao_campanhas',
            name='Telefone',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_esportes',
            name='Telefone',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_games',
            name='Telefone',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='Curso',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='Ra',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='tag',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
