# Generated by Django 3.0.5 on 2020-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0026_auto_20200522_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao_campanhas',
            name='Compareceu',
            field=models.BooleanField(default=False),
        ),
    ]
