# Generated by Django 3.0.5 on 2020-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0027_inscricao_campanhas_compareceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao_campanhas',
            name='email',
            field=models.CharField(default='emaaail', max_length=255),
        ),
    ]
