# Generated by Django 3.0.5 on 2020-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0028_inscricao_campanhas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_campanhas',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
