# Generated by Django 3.0.5 on 2020-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0029_auto_20200522_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhas',
            name='local',
            field=models.CharField(default='local', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_campanhas',
            name='CPF',
            field=models.CharField(default='cpf', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_campanhas',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
