# Generated by Django 3.0.5 on 2020-05-30 01:42

import Avalancheutfpr.services
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0030_auto_20200524_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='diretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('area', models.CharField(max_length=255, unique=True)),
                ('foto', stdimage.models.StdImageField(upload_to=Avalancheutfpr.services.get_file_path)),
                ('video', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
    ]
