# Generated by Django 3.0.6 on 2020-06-03 07:22

import Avalancheutfpr.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0033_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoria',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Avalancheutfpr.services.get_file_path),
        ),
    ]
