# Generated by Django 3.0.6 on 2020-06-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0034_auto_20200603_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='processo_seletivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('Areas', models.CharField(blank=True, max_length=255, null=True)),
                ('Curso', models.CharField(max_length=255, null=True)),
                ('Ra', models.CharField(blank=True, max_length=255)),
                ('Telefone', models.CharField(blank=True, max_length=255)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscrição - Processo Seletivo',
                'verbose_name_plural': 'Inscrições Processo Seletivo',
            },
        ),
    ]
