# Generated by Django 3.0.6 on 2020-06-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0035_processo_seletivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatos',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='processo_seletivo',
            old_name='name',
            new_name='nome',
        ),
    ]
