# Generated by Django 3.0.6 on 2020-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0036_auto_20200609_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo_seletivo',
            name='Areas',
            field=models.CharField(blank=True, help_text='Coloque as areas que deseja participar', max_length=255, null=True),
        ),
    ]
