# Generated by Django 3.0.6 on 2020-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0037_auto_20200609_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contatos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='processo_seletivo',
            name='nome',
        ),
        migrations.AddField(
            model_name='contatos',
            name='name',
            field=models.CharField(default='padrao', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processo_seletivo',
            name='name',
            field=models.CharField(default='padra', max_length=255, unique=True, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inscricao_campanhas',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
