# Generated by Django 3.0.6 on 2020-06-09 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0038_auto_20200609_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo_seletivo',
            options={'verbose_name': 'Processo Seletivo', 'verbose_name_plural': 'Processo Seletivo'},
        ),
        migrations.AddField(
            model_name='inscricao_campanhas',
            name='data',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 9, 14, 18, 27, 931608, tzinfo=utc), verbose_name='Data da inscrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_esportes',
            name='data',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 9, 14, 18, 34, 50215, tzinfo=utc), verbose_name='Data da inscrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_games',
            name='data',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 9, 14, 18, 42, 802116, tzinfo=utc), verbose_name='Data da inscrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Realização'),
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='campanhas',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='games',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='games',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='inscricao_campanhas',
            name='Ra',
            field=models.CharField(max_length=30, verbose_name='Registro Acadêmico'),
        ),
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='Ra',
            field=models.CharField(max_length=30, verbose_name='Registro Acadêmico'),
        ),
        migrations.AlterField(
            model_name='inscricao_games',
            name='Ra',
            field=models.CharField(max_length=30, verbose_name='Registro Acadêmico'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='modalidades',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='processo_seletivo',
            name='Ra',
            field=models.CharField(blank=True, max_length=255, verbose_name='Registro acadêmico'),
        ),
        migrations.AlterField(
            model_name='processo_seletivo',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data da inscrição'),
        ),
    ]
