# Generated by Django 3.0.6 on 2020-06-09 16:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0040_eventos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhas',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='padrao', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='padra', editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modalidades',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='padrao', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
