# Generated by Django 3.0.6 on 2020-06-10 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0041_auto_20200609_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanhas',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Ação Social', 'verbose_name_plural': 'Ações Sociais'},
        ),
        migrations.AlterModelOptions(
            name='contatos',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='diretoria',
            options={'ordering': ['area'], 'verbose_name': 'Diretor', 'verbose_name_plural': 'Diretores'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['name'], 'verbose_name': 'Modalidade de E-sports', 'verbose_name_plural': 'Modalidades de E-sports'},
        ),
        migrations.AlterModelOptions(
            name='inscricao_campanhas',
            options={'ordering': ['Campanha'], 'verbose_name': 'Ações Sociais - inscrições', 'verbose_name_plural': 'Ações Sociais - inscrições'},
        ),
        migrations.AlterModelOptions(
            name='inscricao_esportes',
            options={'ordering': ['modalidade'], 'verbose_name': 'Modalidades - inscrições', 'verbose_name_plural': 'Modalidades - inscrições'},
        ),
        migrations.AlterModelOptions(
            name='inscricao_games',
            options={'ordering': ['Game'], 'verbose_name': 'E-sports - inscrições', 'verbose_name_plural': 'E-sports - inscrições'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['tag'], 'verbose_name': 'mídia', 'verbose_name_plural': ' mídias'},
        ),
        migrations.AlterModelOptions(
            name='modalidades',
            options={'ordering': ['name'], 'verbose_name': 'Modalidade', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AddField(
            model_name='contatos',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 10, 15, 40, 57, 790507, tzinfo=utc), verbose_name='Data do contato'),
            preserve_default=False,
        ),
    ]
