# Generated by Django 3.0.6 on 2020-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0042_auto_20200610_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='tag',
            field=models.CharField(default=0, max_length=100, null=True, unique=True),
        ),
    ]
