# Generated by Django 3.0.6 on 2020-06-21 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Avalancheutfpr', '0043_auto_20200621_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao_esportes',
            name='Curso',
        ),
        migrations.RemoveField(
            model_name='inscricao_esportes',
            name='Ra',
        ),
        migrations.RemoveField(
            model_name='inscricao_esportes',
            name='Telefone',
        ),
        migrations.RemoveField(
            model_name='inscricao_esportes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inscricao_esportes',
            name='tag',
        ),
        migrations.AddField(
            model_name='inscricao_esportes',
            name='usuario',
            field=models.ForeignKey(default='lucas.vinicius@atleticautfpr.com.br', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao_esportes',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.modalidades', verbose_name='Modalidade'),
        ),
    ]
