# Generated by Django 3.0.6 on 2020-06-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Avalancheutfpr', '0044_auto_20200621_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscricao_modalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da inscrição')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.modalidades', verbose_name='Modalidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Modalidades - inscrições',
                'verbose_name_plural': 'Modalidades - inscrições',
                'ordering': ['modalidade'],
            },
        ),
        migrations.DeleteModel(
            name='Inscricao_esportes',
        ),
    ]
