# Generated by Django 3.0.6 on 2020-06-21 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Avalancheutfpr', '0045_auto_20200621_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscricao_campanhas_sociais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compareceu', models.BooleanField(default=False)),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da inscrição')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.campanhas', verbose_name='Campanha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ações Sociais - inscrições',
                'verbose_name_plural': 'Ações Sociais - inscrições',
                'ordering': ['campanha'],
            },
        ),
        migrations.CreateModel(
            name='inscricao_E_sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da inscrição')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avalancheutfpr.games', verbose_name='E-Modalidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'E-sports - inscrições',
                'verbose_name_plural': 'E-sports - inscrições',
                'ordering': ['game'],
            },
        ),
        migrations.CreateModel(
            name='inscricao_processo_seletivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Areas', models.CharField(blank=True, help_text='Coloque as areas que deseja participar', max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Processo Seletivo',
                'verbose_name_plural': 'Processo Seletivo',
            },
        ),
        migrations.DeleteModel(
            name='Inscricao_Campanhas',
        ),
        migrations.DeleteModel(
            name='Inscricao_games',
        ),
        migrations.DeleteModel(
            name='processo_seletivo',
        ),
    ]
