# Generated by Django 3.0.6 on 2020-06-24 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0046_auto_20200621_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 6, 24, 22, 19, 26, 577353, tzinfo=utc), verbose_name='Data de Criação'),
            preserve_default=False,
        ),
    ]
