# Generated by Django 3.0.6 on 2020-07-03 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Avalancheutfpr', '0047_media_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao_campanhas_sociais',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='inscrito', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='inscricao_e_sports',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='inscrito', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='inscricao_modalidades',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='inscrito', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.DeleteModel(
            name='inscricao_processo_seletivo',
        ),
    ]
