# Generated by Django 3.0.6 on 2020-07-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0048_auto_20200703_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao_campanhas_sociais',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='inscricao_e_sports',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='inscricao_modalidades',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inscricao_campanhas_sociais',
            name='Ra',
            field=models.CharField(default=123, max_length=30, verbose_name='Registro Acadêmico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_campanhas_sociais',
            name='curso',
            field=models.CharField(default=123, max_length=255, verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_campanhas_sociais',
            name='email',
            field=models.CharField(default=123, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_campanhas_sociais',
            name='name',
            field=models.CharField(default=123, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_campanhas_sociais',
            name='telefone',
            field=models.CharField(default=99999999, max_length=30, verbose_name='Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_e_sports',
            name='Ra',
            field=models.CharField(default=123, max_length=30, verbose_name='Registro Acadêmico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_e_sports',
            name='curso',
            field=models.CharField(default=123, max_length=255, verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_e_sports',
            name='email',
            field=models.CharField(default=123, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_e_sports',
            name='name',
            field=models.CharField(default=123, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_e_sports',
            name='telefone',
            field=models.CharField(default=99999999999, max_length=30, verbose_name='Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_modalidades',
            name='Ra',
            field=models.CharField(default=123, max_length=30, verbose_name='Registro Acadêmico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_modalidades',
            name='curso',
            field=models.CharField(default=123, max_length=255, verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_modalidades',
            name='email',
            field=models.CharField(default=123, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_modalidades',
            name='name',
            field=models.CharField(default=123, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao_modalidades',
            name='telefone',
            field=models.CharField(default=123, max_length=30, verbose_name='Contato'),
            preserve_default=False,
        ),
    ]
