# Generated by Django 3.0.6 on 2020-07-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avalancheutfpr', '0051_auto_20200704_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidades',
            name='QRcode',
        ),
    ]
