# Generated by Django 3.1.1 on 2020-09-20 04:24

import Avalancheutfpr.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centros de custo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='contasreceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Título')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do recebimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do título')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Juros')),
                ('arquivo', models.FileField(blank=True, upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Nota')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('Custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receber', to='Administrativo.custo', verbose_name='Centro de custo')),
            ],
            options={
                'verbose_name': 'Conta a receber',
                'verbose_name_plural': 'Contas a receber',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='contaspagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Título')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de Vencimento')),
                ('fornecedor', models.CharField(max_length=255, verbose_name='Fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do título')),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Juros')),
                ('barras', models.IntegerField(verbose_name='Código de Barras')),
                ('arquivo', models.FileField(blank=True, upload_to=Avalancheutfpr.services.get_file_path, verbose_name='Nota')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('Custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pagar', to='Administrativo.custo', verbose_name='Centro de custo')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
                'ordering': ['name'],
            },
        ),
    ]
